name: "Chromatic Main Trigger"

on:
  push:
    branches:
      - main
    paths:
      - "src/stories/**"

jobs:
  trigger-chromatic:
    name: Run visual tests
    uses: ./.github/workflows/chromatic.yml
    secrets: inherit
