name: "Chromatic Main Trigger"

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
    paths:
      - "src/stories/**"

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo Hello, world!
