name: "Chromatic Master Trigger"

on:
  push:
    branches:
      - main
    paths:
      - "src/stories/**"
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "packages/**"

jobs:
  trigger-chromatic:
    name: Run visual tests
    uses: ./.github/workflows/chromatic.yml
    secrets: inherit
