name: "Chromatic Trigger"

on:
  push:
    branches:
      - main
    paths:
      - "src/stories/**"
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "src/stories/**"

jobs:
  trigger-chromatic:
    name: Run visual tests
    uses: ./.github/workflows/chromatic.yml
    secrets: inherit
