name: "Chromatic Main Trigger"

on:
  push:
    branches:
      - main
    paths:
      - "src/stories/**"

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check for merge commit
        id: check
        run: echo "::set-output name=isMerge::$(git log --merges -1 --pretty=format:'%H')"
      - name: Print Hello World
        run: echo Hello, world!
        if: steps.check.outputs.isMerge == github.sha
